### ISSUE TITLE
`new FetchPlease` doesn't work for dist/fetch-please.js

### ISSUE THREAD

**Issue by shamrin** [albburtsev/talaria#6]
```
npm install fetch-please
```

``` html
<html><body>
<script src="./node_modules/fetch-please/dist/fetch-please.js"></script>
<script>
    let api = new FetchPlease('https://jsonplaceholder.typicode.com/');
    api.get('users').then((users) => {
        console.log(users);
    });
</script>
</body></html>
```

Then open html file in browser. Notice error in the console:

```
Uncaught TypeError: FetchPlease is not a constructor
```

P.S. `new FetchPlease.default(…)` works

**Comment by albburtsev** [comment]
Unfortunately, I can't implement a straightforward solution without breaking compatibility. I exported constants like `ERROR_UNACCEPTABLE_HTTP_CODE` or `ERROR_XHR_NOT_FOUND`. So, developers can import them in this way:

``` js
import FetchPlease, {ERROR_UNACCEPTABLE_HTTP_CODE} from 'fetch-please';
```

But if I try to use plugin [add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports) and [same for UMD](http://babeljs.io/docs/plugins/transform-es2015-modules-umd/), I will not get expected result, because of [a possible collision with exported constants](https://github.com/59naga/babel-plugin-add-module-exports/issues/27).

I can add constants as static methods of `FetchPlease` class and import constants in this way:

``` js
import FetchPlease from 'fetch-please';

const {ERROR_UNACCEPTABLE_HTTP_CODE} = FetchPlease;
```

But it is less comfy in ES6 syntax and will brake compatibility.

So, I made the decision to save inconvenient syntax `FetchPlease.default` for UMD and CommonJS in favor of ES6.
